name: Webook external dispatch
on:
  repository_dispatch:
    - types: [webhook]

jobs:
  run-on-failure:
    runs-on: ubuntu-latest
    steps:
      - env:
          MESSAGE: $ {{ github.event.client_payload.msg }}
        run: echo $MESSAGE
